# Element-wise operations

If you have a tensor with dimension $(n_1,n_2,...,n_k, ...,n_m)$ and you want to perform some operation on dimension $k$. You need to create a tensor with dimension $(n_k, 1, 1, ..., 1) \in \mathbb{N}^k$. Then you can just use basic algebraic operations.

In [1]:
import torch
import numpy as np

## Two-dimensional example

Suppose you need to add a zero tensor to an array containing two numbers. So in the following cells the tensors `a` and `b` are created, which we will use for example:

In [29]:
np.random.seed(10)

a = torch.zeros((2, 3))
b = torch.tensor([2,3])


print("Tensor a")
print(a)
print("shape - ", list(a.shape), end = "\n\n\n")


print("Tensor b")
print(b)
print("shape - ", list(b.shape))

Tensor a
tensor([[0., 0., 0.],
        [0., 0., 0.]])
shape -  [2, 3]


Tensor b
tensor([2, 3])
shape -  [2]


The added tensor must be converted so that $n_1=m_1$. 

Where :
- $n_i$ - zeros tensor $i-th$ dimention size;
- $m_i$ - addimg tensor $i-th$ dimetion size.

So in the following example we will use `unsqueeze` for this purpose.

In [27]:
b_unsqueezed = b.unsqueeze(1)
print(b_unsqueezed)
print("shape - ", list(b_unsqueezed.shape))

tensor([[2],
        [3]])
shape -  [2, 1]


And finally result of sum. Essentially we just added the corresponding values of array `b` to each element in the row of array `a`:

In [32]:
a + b_unsqueezed

tensor([[2., 2., 2.],
        [3., 3., 3.]])

## Arbitrary dimention example

This shows how to add a tensor of any dimension to another tensor along the selected axis. The following cell creates the tensors we'll use as an example:

In [34]:
np.random.seed(10)

a = torch.zeros((3, 2, 3, 3))
b = torch.tensor([2,3])
print("Tensor a")
print(a)
print("shape - ", list(a.shape), end = "\n\n\n")

print("Tensor b")
print(b)Transformation of the adding tensor to the power sum:
print("shape - ", list(b.shape))

Tensor a
tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])
shape -  [3, 2, 3, 3]


Tensor b
tensor([2, 3])
shape -  [2]


Transformation of adding tensor to pefrorm sum:

In [36]:
b_unsqueezed = b.unsqueeze(1).unsqueeze(1)
print("tensor")
print(b_unsqueezed)
print("shape - ", list(b_unsqueezed.shape))

tensor
tensor([[[2]],

        [[3]]])
shape -  [2, 1, 1]


And finally do the sum. So for each $i-th; i \in \overline{1,n_k}$ within the tensor with dimension $(n_{k+1},...,n_{m})$ the $i-th$ number from the adding tensor is added. 

In [137]:
a+b_unsqueezed

tensor([[[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[3., 3., 3.],
          [3., 3., 3.],
          [3., 3., 3.]]],


        [[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[3., 3., 3.],
          [3., 3., 3.],
          [3., 3., 3.]]],


        [[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[3., 3., 3.],
          [3., 3., 3.],
          [3., 3., 3.]]]])