# Differentiation

Torch has tools that allow you to calculate derivatives. This page created for this feature.

In [1]:
import torch

## Basic

To compute derivative in torch you need to create `torch.tensor` with the property `requires_grad = True` so that torch will look for the gradient of any function this tensor is involved in.

Then we need to define a function that depends on the tensor under consideration. And call the `backward` method from it - it will compute partial derivatives for each tensor on which it depends.

After previous step you will have derivative values in `grad` field of tensor under consideration.

### Example 1

Let's say we have function:

$$y(\omega)=\sum_i^n 3\omega_i.$$

And we need to find the derivative of the function on the variables $\omega_i, i\in\overline{1,n}$. Let's do it by hand at first:

$$\frac{dy}{d \omega_i} = \sum_j^n\frac{d3\omega_j}{d \omega_i} = \sum_j^n3\frac{d\omega_j}{d \omega_i}.$$

And that's considering the fact that:

$$\frac{d \omega_i}{d \omega_j} = \begin{cases} 0 , i\neq j; \\ 1 , i=j.\end{cases}$$

We got:

$$\frac{dy}{d \omega_i} = 3.$$

The implementation of this example in Torch is listed in the cell below:

In [16]:
n = 5
w = torch.rand(n, requires_grad = True)
y = torch.sum(w*3)
y.backward()
w.grad

tensor([3., 3., 3., 3., 3.])

### Example 2

Now we have a slightly more complicated function:

$$y(\omega, \gamma)=\sum_i^n \omega_i \gamma_i.$$

So derivatives by $\omega_i$ and $\gamma_i, i \in \overline{1,n}$ accordingly:

$$\frac{dy}{d \omega_i} = \sum_j^n\frac{d\omega_j\gamma_j}{d \omega_i} = \sum_j^n\gamma_j\frac{d\omega_j}{d \omega_i}=\gamma_i;$$
$$\frac{dy}{d \gamma_i} = \sum_j^n\frac{d\omega_j\gamma_j}{d \gamma_i} = \sum_j^n\omega_j\frac{d\gamma_j}{d \gamma_i}=\omega_i.$$

And the implementation in the Torch for this case will look like the following cell. The main purpose of this example is to show that if the derivative contains a variable, its value is substituted into the expression. So in the example:

- $\omega=(1,2,3,4)$ - so derivatives of the $\gamma_i$ take these values;
- likewise $\gamma=(5,6,7,8)$ - derivatvies of the $\omega_i$ take these values.

In [31]:
w = torch.tensor([1, 2, 3, 4], dtype = torch.float, requires_grad = True)
g = torch.tensor([5, 6, 7, 8], dtype = torch.float, requires_grad = True)

y = torch.matmul(w, g)
y.backward()
print("omega gradient value")
print(w.grad)
print("gamma gradient value")
print(g.grad)

omega gradient value
tensor([5., 6., 7., 8.])
gamma gradient value
tensor([1., 2., 3., 4.])
