# Tensor

Here is a description of the basic data type in PyTorch: `torch.Tensor`.

In [3]:
import torch
import numpy as np

## Create tensor

Torch has tons of methods to create tensors. [This page](tensor/creating_methods.ipynb) lists the methods I know for now.

---

The most **straightforward** way is to use `torch.tensor`.

In [ ]:
torch.Tensor(3,2,5)

tensor([[[ 0.0000e+00,  0.0000e+00,  1.4013e-45,  0.0000e+00,  1.4013e-45],
         [ 0.0000e+00,  9.1084e-44,  0.0000e+00, -3.7852e+06,  3.3707e-41]],

        [[-7.6466e+07,  3.3707e-41,  4.4842e-44,  0.0000e+00,  4.4842e-44],
         [ 0.0000e+00,  6.3884e-27,  3.3703e-41,  0.0000e+00,  1.4013e-45]],

        [[ 1.3004e-42,  0.0000e+00,  1.1210e-43,  0.0000e+00,  6.4326e-27],
         [ 3.3703e-41,  4.2427e-08,  1.2964e+16,  2.1707e-18,  7.0952e+22]]])

## Shape

Simply refer to the `shape` attribute to get the dimensionality of the tensor. You will got `torch.Size` as the result, you can use `[]` to access values of this object.

In [22]:
shape_return = torch.tensor([[1,2,3], [1,2,3]]).shape
display(shape_return)
print(f"rows : {shape_return[0]}, columns: {shape_return[1]}")

torch.Size([2, 3])

rows : 2, columns: 3


## Data type

Torch has it's own system of data types. Here is a table that describes the available datatypes.


| Type       | Description                                |
|------------|--------------------------------------------|
| `torch.float16` / `torch.half`  | 16-bit half precision (floating point)       |
| `torch.float32` / `torch.float` | 32-bit single precision (floating point)     |
| `torch.float64` / `torch.double`| 64-bit double precision (floating point)     |
| `torch.int8`                    | 8-bit integer                                |
| `torch.int16` / `torch.short`   | 16-bit integer                               |
| `torch.int32` / `torch.int`     | 32-bit integer                               |
| `torch.int64` / `torch.long`    | 64-bit integer                               |
| `torch.uint8`                   | 8-bit unsigned integer                       |
| `torch.bool`                    | Boolean type                                 |
| `torch.complex64`               | 64-bit complex number (32-bit real and imaginary) |
| `torch.complex128`              | 128-bit complex number (64-bit real and imaginary) |


---

You can get type of the tensor by using `dtype` field.

In [15]:
torch.Tensor(3, 3).dtype

torch.float32

**Note** there are some functions in torch that have `dtype` parameter. By passing special torch objects as `dtype` arguments, we can get tensors of the specific dtype.

In [16]:
torch.tensor([1,2,3], dtype=torch.float16)

tensor([1., 2., 3.], dtype=torch.float16)

In [18]:
torch.zeros((3,3), dtype=torch.float16)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)