# Tensor

Here is a description of the basic data type in PyTorch: `torch.Tensor`.

In [1]:
import torch
from math import prod

## Create tensor

Torch has tons of methods to create tensors. [This page](tensor/creating_methods.ipynb) lists the methods I know for now.

---

The most **straightforward** way is to use `torch.tensor`.

In [ ]:
torch.Tensor(3,2,5)

tensor([[[ 0.0000e+00,  0.0000e+00,  1.4013e-45,  0.0000e+00,  1.4013e-45],
         [ 0.0000e+00,  9.1084e-44,  0.0000e+00, -3.7852e+06,  3.3707e-41]],

        [[-7.6466e+07,  3.3707e-41,  4.4842e-44,  0.0000e+00,  4.4842e-44],
         [ 0.0000e+00,  6.3884e-27,  3.3703e-41,  0.0000e+00,  1.4013e-45]],

        [[ 1.3004e-42,  0.0000e+00,  1.1210e-43,  0.0000e+00,  6.4326e-27],
         [ 3.3703e-41,  4.2427e-08,  1.2964e+16,  2.1707e-18,  7.0952e+22]]])

## Dimentionality

One of the most important properties of the tensor is it's dimensionality. Torch provides a set of tools to manage tensor dimensionality. Find out more on the [dedicated page](tensor/dimentionality.ipynb).

---

The most important tools is:

- `shape` attribute that contains dimentionality.
- `reshape` method that allows to change dimentionality of the tensor.

The fillowing cell shows both of them.

In [10]:
test_tensor = torch.zeros(2, 5, 3)
print('torch.Tensor.shape', test_tensor.shape)
test_tensor.reshape(6, 5)

torch.Tensor.shape torch.Size([2, 5, 3])


tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

## Indexing

Indexing in `torch` supports all the classic condepts, just like in `numpy` or `pandas`. But there are some features specific for `torch` findout more in the [specific page](tensor/indexing.ipynb).

---

The following example shows the most basic methods of indexing in Torch. For the first dimensionality it takes all available elements, for the second it takes the slice `0:5:2` and along the last dimensionality it takes the elements counted in `list`.

In [31]:
dimentionality = (2,6,6)
experimental = torch.arange(prod(dimentionality)).reshape(dimentionality)

print("Original tensor")
print(experimental)
print("Sliced tensor")
print(experimental[:, 0:5:2, [5,1,4]])

Original tensor
tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11],
         [12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23],
         [24, 25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34, 35]],

        [[36, 37, 38, 39, 40, 41],
         [42, 43, 44, 45, 46, 47],
         [48, 49, 50, 51, 52, 53],
         [54, 55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64, 65],
         [66, 67, 68, 69, 70, 71]]])
Sliced tensor
tensor([[[ 5,  1,  4],
         [17, 13, 16],
         [29, 25, 28]],

        [[41, 37, 40],
         [53, 49, 52],
         [65, 61, 64]]])


## Element-wise operations

There is a class of operations in Pytorch that are applied element by element - we'll call them element wise operations. Read more in the [special page](tensor/element_wise.ipynb).

---

As a brief review, consider two matrices $A = [a_{ij}]_{n \times m}$ and $B = [b_{ij}]_{n \times m}$. 

In [4]:
A = torch.randint(-5,5, [4,5])
A

tensor([[-5, -2,  4,  0, -4],
        [-1, -4,  1, -5, -5],
        [-4,  1,  4, -5, -5],
        [-2,  2,  0,  1,  0]])

In [5]:
B = torch.randint(-5,5, [4,5])
B

tensor([[-1, -3,  1, -4, -4],
        [-4,  4, -4, -4, -3],
        [ 3, -2,  0, -1,  0],
        [ 4, -2,  0,  2,  1]])

By applying the `+` operator to matrices we got the matrix $\left[a_{ij} + b_{ij}\right]_{n \times m}$ - so the operation was applied element by element.

In [7]:
A + B

tensor([[-6, -5,  5, -4, -8],
        [-5,  0, -3, -9, -8],
        [-1, -1,  4, -6, -5],
        [ 2,  0,  0,  3,  1]])

## Algebraic operations

The following table lists algebraic operations on `torch.Tensor`.

| **Operation**                 | **Function**                  | **Description**                           |
|-------------------------------|-------------------------------|-------------------------------------------|
| Matrix Multiplication         | `torch.matmul()`              | Matrix multiplication                    |
|                               | `tensor1 @ tensor2`           | Matrix multiplication using `@` operator |
| Singular Value Decomposition  | `torch.svd()`                 | Singular Value Decomposition (SVD)        |
|                               | `torch.linalg.svd()`          | SVD with advanced options                |
| Eigenvalues and Eigenvectors  | `torch.eig()`                 | Compute eigenvalues and eigenvectors     |
|                               | `torch.linalg.eig()`          | Eigenvalues and eigenvectors (advanced)  |
| Matrix Inversion              | `torch.linalg.inv()`          | Matrix inversion                          |
|                               | `torch.inverse()`             | Matrix inversion (deprecated)            |
| Matrix Norms                  | `torch.norm()`                | Compute the norm of a tensor             |
|                               | `torch.linalg.norm()`         | Norm with advanced options               |
| Determinants                  | `torch.det()`                 | Compute the determinant of a matrix       |
|                               | `torch.linalg.det()`          | Determinant with advanced options        |
| Matrix Trace                  | `torch.trace()`               | Compute the trace of a matrix            |
| Eigenvalues                   | `torch.linalg.eigvals()`      | Compute eigenvalues of a square matrix   |
| Matrix Rank                   | `torch.linalg.matrix_rank()`  | Compute the rank of a matrix             |
| Cholesky Decomposition        | `torch.linalg.cholesky()`     | Cholesky decomposition                    |
| QR Decomposition              | `torch.linalg.qr()`           | QR decomposition                          |
| Solving Linear Systems        | `torch.linalg.solve()`        | Solve a system of linear equations       |
|                               | `torch.linalg.lstsq()`        | Solve a least-squares problem            |
| Kronecker Product             | `torch.kron()`                | Compute the Kronecker product             |

## Data type

Torch has it's own system of data types. Here is a table that describes the available datatypes.


| Type       | Description                                |
|------------|--------------------------------------------|
| `torch.float16` / `torch.half`  | 16-bit half precision (floating point)       |
| `torch.float32` / `torch.float` | 32-bit single precision (floating point)     |
| `torch.float64` / `torch.double`| 64-bit double precision (floating point)     |
| `torch.int8`                    | 8-bit integer                                |
| `torch.int16` / `torch.short`   | 16-bit integer                               |
| `torch.int32` / `torch.int`     | 32-bit integer                               |
| `torch.int64` / `torch.long`    | 64-bit integer                               |
| `torch.uint8`                   | 8-bit unsigned integer                       |
| `torch.bool`                    | Boolean type                                 |
| `torch.complex64`               | 64-bit complex number (32-bit real and imaginary) |
| `torch.complex128`              | 128-bit complex number (64-bit real and imaginary) |


---

You can get type of the tensor by using `dtype` field.

In [15]:
torch.Tensor(3, 3).dtype

torch.float32

**Note** there are some functions in torch that have `dtype` parameter. By passing special torch objects as `dtype` arguments, we can get tensors of the specific dtype.

In [16]:
torch.tensor([1,2,3], dtype=torch.float16)

tensor([1., 2., 3.], dtype=torch.float16)

In [18]:
torch.zeros((3,3), dtype=torch.float16)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)

## Inplace methods

Some methods of `torch.Tensor` allow you to change the value of the tensor on the fly. It's typical for such methods to have the underscore symbol `_` at the end of the name.

| Method                       | Description                                                                                       |
|------------------------------|---------------------------------------------------------------------------------------------------|
| `add_`                       | Adds the input tensor to the current tensor in place.                                             |
| `addcmul_`                   | Performs a component-wise multiplication of two tensors and adds the result to the current tensor in place. |
| `addcdiv_`                   | Performs a component-wise division of two tensors and adds the result to the current tensor in place. |
| `bernoulli_`                 | Applies the Bernoulli distribution to the tensor in place.                                        |
| `bmm_`                       | Performs batch matrix multiplication in place.                                                   |
| `clamp_`                     | Clamps all elements in the input tensor to be within the specified range, in place.              |
| `copy_`                      | Copies data from another tensor to the current tensor in place.                                    |
| `div_`                       | Divides the current tensor by the input tensor in place.                                          |
| `fill_`                      | Fills the tensor with the specified value in place.                                               |
| `flatten_`                   | Flattens the tensor to a 1D tensor in place.                                                     |
| `index_add_`                 | Adds values to the tensor at specified indices in place.                                          |
| `index_fill_`                | Fills the tensor at specified indices with the given value in place.                              |
| `index_copy_`                | Copies values from another tensor into the current tensor at specified indices, in place.         |
| `mask_fill_`                 | Fills elements of the tensor where the mask is `True` with the specified value in place.           |
| `mask_scatter_`              | Scatters values into the tensor at indices specified by the mask in place.                        |
| `masked_fill_`               | Fills elements of the tensor where the mask is `True` with the specified value in place.           |
| `masked_scatter_`            | Scatters values into the tensor where the mask is `True` in place.                                 |
| `neg_`                       | Negates the tensor's values in place.                                                             |
| `normal_`                    | Fills the tensor with random numbers from a normal distribution in place.                         |
| `relu_`                      | Applies the ReLU activation function in place.                                                    |
| `renorm_`                    | Renormalizes the tensor along a specified dimension in place.                                     |
| `scatter_`                   | Scatters values into the tensor at specified indices in place.                                    |
| `select_`                    | Selects a sub-tensor in place (used for slicing).                                                 |
| `set_`                       | Sets tensor values based on other tensors or values in place.                                      |
| `sigmoid_`                   | Applies the sigmoid function in place.                                                            |
| `softmax_`                   | Applies the softmax function in place along a specified dimension.                                |
| `sub_`                       | Subtracts the input tensor from the current tensor in place.                                      |
| `t_`                         | Transposes the tensor in place (2D tensors only).                                                 |
| `transpose_`                 | Transposes the tensor along specified dimensions in place.                                        |
| `truncate_`                  | Truncates tensor values to a specified precision in place.                                         |
| `zero_`                      | Sets all elements of the tensor to zero in place.                                                  |


Here is an example of applying the `relu` transformation to the tensor.

In [30]:
my_tensor = torch.arange(-1,1,0.1)
my_tensor.relu_()
my_tensor

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000,
        0.8000, 0.9000])

## Repeat method

The `torch.Tensor.repeat` function allows you to duplicate a tensor's values along specific dimensions, creating a new tensor with the replicated values. 

---

For example, consider a tensor created using `torch.arange(0, 2)`.

In [9]:
example_array = torch.arange(3)
example_array

tensor([0, 1, 2])

If you use `repeat` along a nested axis (e.g., `repeat(3)`), the input vector is duplicated three times, resulting in a longer vector. 

In [10]:
example_array.repeat(3)

tensor([0, 1, 2, 0, 1, 2, 0, 1, 2])

By replicating along the rows (e.g., `repeat(3, 1)`), you will create a matrix with three rows. Each row will contain a copy of the original input vector. 

In [5]:
torch.arange(3).repeat(3, 1)

tensor([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]])

Finally, let's try to duplicate the vector three times vertically and two times in the depth dimension. This will create a tensor with three columns, each containing a duplicated version of the original vector, and two layers of these duplicated columns.

In [8]:
torch.arange(3).repeat(2, 3, 1)

tensor([[[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]],

        [[0, 1, 2],
         [0, 1, 2],
         [0, 1, 2]]])