# Broadcasting

Broadcasting is a mechanism that allows tensors of different shapes to be used together in element-wise operations.

In [2]:
import torch

## By row

Suppose you need to add a zero tensor to an array containing two numbers. So in the following cells the tensors `a` and `b` are created, which we will use for example:

In [3]:
a = torch.zeros((2, 3))
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
b = torch.tensor([2, 3])
b

tensor([2, 3])

So suppose we want to add the first element of `b` to the first row of `a` and the second element of `b` to the second row of `a`. Obviously just using operator `+` won't work.

In [6]:
a + b

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

The added tensor must be converted so that $n_1=m_1$. 

Where :
- $n_i$ - zeros tensor $i-th$ dimention size;
- $m_i$ - addimg tensor $i-th$ dimetion size.

So in the following example we will use `unsqueeze` for this purpose.

In [5]:
b_unsqueezed = b.unsqueeze(1)
b_unsqueezed

tensor([[2],
        [3]])

And finally result of sum. Essentially we just added the corresponding values of array `b` to each element in the row of array `a`:

In [7]:
a + b_unsqueezed

tensor([[2., 2., 2.],
        [3., 3., 3.]])

## By layer

This shows how to add a tensor of any dimension to another tensor along the selected axis. 

---

The following cell creates a tensor with the dimensionality `(3, 2, 3, 3)`. We'll interpret this as 3 cubes with 2 layers, 3 rows and 3 columns.

In [10]:
a = torch.zeros((3, 2, 3, 3))
a

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]])

Suppose we need to add same number to the corresponding layer of each cube. Let it be 2 for first layer and 3 for second layer. So we have to create tensor with dimentions `(2,1,1)` - which you can understand as two elements in different layers.

In [19]:
b = torch.tensor([[[2]], [[3]]])
print(b)
print(b.shape)

tensor([[[2]],

        [[3]]])
torch.Size([2, 1, 1])


Now perform an addition operation on the corresponding layer of each cube.

In [21]:
a + b

tensor([[[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[3., 3., 3.],
          [3., 3., 3.],
          [3., 3., 3.]]],


        [[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[3., 3., 3.],
          [3., 3., 3.],
          [3., 3., 3.]]],


        [[[2., 2., 2.],
          [2., 2., 2.],
          [2., 2., 2.]],

         [[3., 3., 3.],
          [3., 3., 3.],
          [3., 3., 3.]]]])