# Creating methods

This page looks at different ways of creating a tensor in Pytorch.

In [2]:
import torch

## Allocating memory

`torch.Tensor` just allocates memory for the tensor and uses the values that is still there from previous processes.

In [2]:
torch.Tensor(3,2,5)

tensor([[[-7.5724e+09,  4.1862e-41, -7.5724e+09,  4.1862e-41,  4.4377e+27],
         [ 7.2143e+22,  4.7987e+30,  1.9887e+23,  1.0893e+27,  4.1576e+21]],

        [[ 7.3697e+28,  7.1221e+28,  1.9349e-19,  2.0535e-19,  1.9284e+31],
         [ 1.9431e-19,  1.8976e+37,  6.6522e-33,  1.3563e-19,  7.4409e+28]],

        [[ 1.2713e+31,  1.8499e+20,  1.6078e+19,  3.2770e+09,  1.7689e+31],
         [ 1.6460e+19,  7.1435e+31,  1.8177e+31,  6.8292e+22,  7.8979e+34]]])

## Specify values

For creating tensor **with specified** values use `torch.tensor`.

In [3]:
torch.tensor([[1,2,3], [3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

## Random distributions

There are some functions in Torch that allow you to generate arrays of what values belong to the particle distribution. Such function listed in the following table:

| Function             | Description                                                                                      |
|----------------------|--------------------------------------------------------------------------------------------------|
| `torch.rand`         | Generates a tensor with random values from a uniform distribution in the range [0, 1).           |
| `torch.randn`        | Generates a tensor with random values from a standard normal distribution (mean 0, variance 1). |
| `torch.randint`      | Generates a tensor with random integers within a specified range.                               |
| `torch.normal`       | Generates a tensor with random values from a normal distribution with specified mean and std. dev. |
| `torch.uniform`      | Generates a tensor with random values from a uniform distribution within a specified range.     |
| `torch.bernoulli`    | Generates a tensor of random binary values drawn from a Bernoulli distribution with specified probability of success. |
| `torch.multinomial`  | Generates a tensor of indices drawn from a multinomial distribution based on specified probabilities. |
| `torch.categorical`  | Generates a tensor of indices drawn from a categorical distribution based on specified probabilities. |
| `torch.manual_seed`  | Seeds the random number generator to ensure reproducibility.                                     |

Some of them considered closer in the [specific page](creating_methods/random_distributions.ipynb).

---

Here is example of using `torch.rand`.

In [4]:
torch.rand(3, 3, 3)

tensor([[[0.1544, 0.3327, 0.8823],
         [0.7947, 0.1878, 0.3090],
         [0.3538, 0.1027, 0.3000]],

        [[0.2457, 0.3978, 0.9850],
         [0.8457, 0.8203, 0.3024],
         [0.0055, 0.9485, 0.3854]],

        [[0.7654, 0.3898, 0.1176],
         [0.0242, 0.6451, 0.4490],
         [0.8737, 0.9906, 0.2242]]])

## Same values

There are many cases where you need a tensor that contains all the same values. This section shows some related functions.

With `torch.zeros` you can generate all zeros.

In [21]:
torch.zeros(2, 2, 2)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

With `torch.ones` you can generate all ones.

In [22]:
torch.ones(2, 2, 2)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

With `torch.full` you can generate array filled with specified value.

In [10]:
torch.full([2, 4], 8)

tensor([[8, 8, 8, 8],
        [8, 8, 8, 8]])

## Dimentionality like

There are a number of functions in torch that generate arrays that copy dimensionality from given array. It's typical if they end with `_like` pattern. Such known functions are listed in the following table.

| Function            | Description                                                               |
|---------------------|---------------------------------------------------------------------------|
| `empty_like`        | Returns a tensor with the same size as the input tensor, but with uninitialized data. |
| `full_like`         | Returns a tensor with the same size as the input tensor, filled with a specified value. |
| `ones_like`         | Returns a tensor with the same size as the input tensor, filled with ones. |
| `rand_like`         | Returns a tensor with the same size as the input tensor, filled with random values from a uniform distribution. |
| `randint_like`      | Returns a tensor with the same size as the input tensor, filled with random integers within a specified range. |
| `randn_like`        | Returns a tensor with the same size as the input tensor, filled with random values from a normal distribution. |
| `zeros_like`        | Returns a tensor with the same size as the input tensor, filled with zeros. |


Here is an example of using `torch.randint_like`, which is actually the same as `torch.randint` but follows the dimentionality of the input tensor.

In [4]:
torch.randint_like(torch.Tensor(10,10), 0, 10)

tensor([[9., 2., 8., 0., 1., 0., 4., 4., 5., 0.],
        [1., 2., 9., 2., 2., 8., 5., 0., 7., 9.],
        [4., 2., 2., 5., 5., 9., 7., 6., 0., 7.],
        [5., 5., 5., 7., 7., 0., 6., 1., 4., 2.],
        [3., 5., 3., 9., 2., 4., 2., 2., 4., 5.],
        [7., 5., 2., 0., 9., 8., 4., 8., 1., 7.],
        [8., 5., 2., 2., 4., 2., 7., 9., 3., 8.],
        [9., 0., 0., 0., 9., 7., 9., 6., 9., 7.],
        [8., 9., 7., 1., 7., 4., 1., 0., 2., 6.],
        [1., 2., 8., 8., 0., 7., 2., 3., 1., 9.]])

## Unit matrix

The `torch.eye` function allows you to create a unit matrix.

In [3]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])