# Creating methods

This page looks at different ways of creating a tensor in Pytorch.

In [1]:
import torch

## Allocating memory

`torch.Tensor` just allocates memory for the tensor and uses the values that is still there from previous processes.

In [2]:
torch.Tensor(3,2,5)

tensor([[[1.0893e+27, 4.1576e+21, 7.3697e+28, 7.1221e+28, 1.9349e-19],
         [2.0535e-19, 1.9284e+31, 1.9431e-19, 1.8976e+37, 6.6522e-33]],

        [[1.3563e-19, 7.4409e+28, 1.2713e+31, 1.8499e+20, 1.6078e+19],
         [3.2770e+09, 1.7689e+31, 1.6460e+19, 7.1435e+31, 1.8177e+31]],

        [[6.8292e+22, 7.8979e+34, 1.3556e-19, 4.5093e+27, 7.6831e+31],
         [6.7593e+34, 1.8523e+28, 2.0615e-19, 9.2072e+11, 3.1410e+03]]])

## Specify values

For creating tensor **with specified** values use `torch.tensor`.

In [8]:
torch.tensor([[1,2,3], [3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

## Random values

For creating tensor **with random** values use `torch.random`.

In [5]:
torch.rand(3, 3, 3)

tensor([[[0.7251, 0.5233, 0.8536],
         [0.4629, 0.3222, 0.2826],
         [0.3703, 0.0113, 0.4685]],

        [[0.8505, 0.9528, 0.5060],
         [0.4150, 0.9585, 0.5233],
         [0.0917, 0.4805, 0.4773]],

        [[0.0570, 0.8759, 0.6732],
         [0.5330, 0.1398, 0.1227],
         [0.3241, 0.3911, 0.4317]]])