# Dimentionality

Dimentionality is a crucial property of the tensor, so it's important to know the torch tools to manage dimentionality.

In [12]:
import torch
from random import randint

test_tensor = torch.zeros([randint(2, 10) for i in range(randint(3, 6))])

## Get

There are two methods to get `torch.Tensor` dimentionality to use `torch.Tensor.shape` attribute or to use `torch.Tensor.size` methods.

---

In the follwing cells both methods were applied to the `test_tensor`.

In [13]:
test_tensor.shape

torch.Size([4, 6, 6, 3, 5, 2])

In [14]:
test_tensor.size()

torch.Size([4, 6, 6, 3, 5, 2])

### `torch.Size`

`torch.Size` object keeps dimentionality in it. It have some features:

Typical Python indexing methods.

In [37]:
tens = torch.zeros([randint(2,6) for i in range(7)])
print("Original shape", tens.shape)
print("Shape slice", tens.shape[1:5])

Original shape torch.Size([6, 6, 5, 4, 2, 3, 2])
Shape slice torch.Size([6, 5, 4, 2])


Some operators will have meaning when used with certain types of data. 
For example, `==` works with `tuple` or `list`.

In [24]:
tens = torch.Tensor(4,3)
(
    tens.shape == (4, 3), 
    tens.shape == [3, 1]
)

(True, False)

## Null dimentional tensors

In PyTorch, there are "null-dimensional" tensors, which are tensors with a single value. In such cases, the tensor appears without any square brackets denoting its dimensionality. For example, when we print the tensor, it doesn't show any brackets to indicate it's a single value. When we print its shape, it displays an empty list, signifying that the tensor has no dimensions.

In [38]:
example_tensor = torch.tensor(3)
print(example_tensor)
print(example_tensor.shape)

tensor(3)
torch.Size([])


## Change dimentionality

The easiest way to change the dimensionality of a tensor is to use the `torch.reshape` function or `torch.torch.reshape` method of the tensor you're reshaping. All you have to do is specify a new dimensionality, quite obviously the number of elements in the new dimensionality must be equal to the number of elements in the tensor to be reshaped.

---

Consider an example with 12 arange elements.

In [52]:
original_tensor = torch.arange(12)
print("original", original_tensor)

original tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


The following cell reshapes it to the `(6, 2)` dimensionality.

In [53]:
original_tensor.reshape(6,2)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

The elements are sequentially obtained in their order, and first fill the innermost dimension, then the next one, and so on.

Same result with more complex result dimentionality.

In [54]:
original_tensor.reshape(3,2,2)

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

Similarly, when reshaping complex dimensions, it will extract elements from the most nested dimensions. The following example breaks the original sequence of elements with transposition, and then reshapes the resulting array to the 1D dimensionality.

In [67]:
transposed_tensor = original_tensor.reshape(2, 6).T
print("Transposed \n", transposed_tensor)

transposed_tensor.reshape(12)

Transposed 
 tensor([[ 0,  6],
        [ 1,  7],
        [ 2,  8],
        [ 3,  9],
        [ 4, 10],
        [ 5, 11]])


tensor([ 0,  6,  1,  7,  2,  8,  3,  9,  4, 10,  5, 11])

It takes elements from inndermost dimentionalty gradually moving to more and more external dimensions. 