# Dimentionality

Dimentionality is a crucial property of the tensor, so it's important to know the torch tools to manage dimentionality.

In [1]:
import torch
from random import randint

## Get

There are two methods to get `torch.Tensor` dimentionality to use `torch.Tensor.shape` attribute or to use `torch.Tensor.size` methods.

---

In the follwing cells both methods were applied to the `test_tensor`.

In [4]:
test_tensor = torch.zeros([randint(2, 10) for i in range(randint(3, 6))])

In [5]:
test_tensor.shape

torch.Size([8, 10, 9, 4, 3])

In [6]:
test_tensor.size()

torch.Size([8, 10, 9, 4, 3])

### `torch.Size`

`torch.Size` object keeps dimentionality in it. It have some features:

Typical Python indexing methods.

In [37]:
tens = torch.zeros([randint(2,6) for i in range(7)])
print("Original shape", tens.shape)
print("Shape slice", tens.shape[1:5])

Original shape torch.Size([6, 6, 5, 4, 2, 3, 2])
Shape slice torch.Size([6, 5, 4, 2])


Some operators will have meaning when used with certain types of data. 
For example, `==` works with `tuple` or `list`.

In [24]:
tens = torch.Tensor(4,3)
(
    tens.shape == (4, 3), 
    tens.shape == [3, 1]
)

(True, False)

## Null dimentional tensors

In PyTorch, there are "null-dimensional" tensors, which are tensors with a single value. In such cases, the tensor appears without any square brackets denoting its dimensionality. For example, when we print the tensor, it doesn't show any brackets to indicate it's a single value. When we print its shape, it displays an empty list, signifying that the tensor has no dimensions.

In [38]:
example_tensor = torch.tensor(3)
print(example_tensor)
print(example_tensor.shape)

tensor(3)
torch.Size([])


## Reshape

The `torch.tensor.reshape` method ro `torch.reshape` function allows you to change the dimensionality of a tensor while preserving the order of its elements. The order is determined by filling elements from the innermost dimension first, then moving to the next dimension, and so on. This order is maintained in the reshaped tensor, but adapted to the new dimensionality.

Find out more int [particular page](dimentionality/reshape.ipynb).

---

As an example, consider a flat tensor (vector).

In [7]:
example = torch.arange(12)
example

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Using the `torhc.tensor.reshape` method, we composed a 3x4 matrix from the elements of the original tensor.

In [9]:
example = example.reshape([3, 4])
example

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Using the `torch.reshape` function, we obtained a 3-dimensional tensor with the original elements.

In [10]:
torch.reshape(example, (2,3,2))

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])

## Transpose

The `transpose` operatin changes counting elements in the tensor. So if we had matrix like $\left[x_{ij}\right]_{nm}$ after transposing we'll have matrix like $\left[x_{ji}\right]_{mn}$. Find out more in the [specific page](dimentionality/transpose.ipynb).

---

The following cell shows the application of the transpose in the two-dimensional case.

In [13]:
example = torch.arange(12).reshape([3, 4])
example

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [14]:
example.transpose(0,1)

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

## Add dimention

Adding an extra dimension to a tensor can be beneficial, particularly when performing matrix multiplication.

All methods of creating a new dimension will result in a new axis being created at the specified position. Each element at the specified position will be transformed into a one-element array along this new axis. Find out more in the [specific page](dimentionality/add_dimention.ipynb).

---

The following example is a quick overview of this operation. For a matrix, it inserts a rows dimension using a `None` index and a columns dimension using the `unsqueeze` method. 

In [63]:
show_tensor = torch.arange(15).reshape(5,3)
display(show_tensor)

display(show_tensor[:, None])
display(show_tensor.unsqueeze(-1))

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

tensor([[[ 0,  1,  2]],

        [[ 3,  4,  5]],

        [[ 6,  7,  8]],

        [[ 9, 10, 11]],

        [[12, 13, 14]]])

tensor([[[ 0],
         [ 1],
         [ 2]],

        [[ 3],
         [ 4],
         [ 5]],

        [[ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11]],

        [[12],
         [13],
         [14]]])

## Remove dimention

The `torch.squeeze` function and the `torch.Tensor.squeeze` method remove dimensions from a tensor that have a size of one. These dimensions are considered "ambiguous" as they contain only a single value. Find out more in [corresponding page](dimentionality/squeeze.ipynb).

---

Consider a tensor containing a few 3D objects. These objects are actually single rows wrapped as 3D layers, with each element being a 1-element vector. 

In [12]:
example_tensor = torch.arange(15).reshape(3, 1, 5, 1)
example_tensor

tensor([[[[ 0],
          [ 1],
          [ 2],
          [ 3],
          [ 4]]],


        [[[ 5],
          [ 6],
          [ 7],
          [ 8],
          [ 9]]],


        [[[10],
          [11],
          [12],
          [13],
          [14]]]])

By applying the `squeeze` method we got just a matrix, so any 3D tensor with ambiguous values becomes just a vector.

In [14]:
example_tensor.squeeze()

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])