# Indexing

In [8]:
import torch
from math import prod

experimental = torch.arange(12).reshape(3, 4)

## All elements along axis

You can access elements from specific dimensions in a tensor using index notation within square brackets. Simply pass the desired indexes to retrieve values from corresponding rows, columns, or other dimensions. If you want to include all elements along a particular dimension without subsampling, use the `:` operator, which signifies 'take all elements' along the specified axis. Check following example:

In [9]:
print("row 1", experimental[1])
print("column 3", experimental[:, 3])

row 1 tensor([4, 5, 6, 7])
column 3 tensor([ 3,  7, 11])


## Slicing

Torch indexing support slicing. The following example selects 0-th and 2-nd columns from experimental tensor.

In [10]:
experimental[:, 0:4:2]

tensor([[ 0,  2],
        [ 4,  6],
        [ 8, 10]])

## Iterable oject

It is also possible to **use iterable objects** to select subtensors from the original tensor. The following example demonstrates using a `list` to select the second and third rows from the end of the tensor.

In [11]:
experimental[[-2,-3]]

tensor([[4, 5, 6, 7],
        [0, 1, 2, 3]])

## New dimention

Using `None` in indexing allows you to add new dimensions to the tensor. It'll add dimetion on the axis `None` displayed on.

---

As example, we'll considering two dimention tensor created in the following cell.

In [49]:
none_example_tensor = torch.arange(12).reshape(4,3)
none_example_tensor

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

By putting `None` at the top, we've got a new outer axis, so the whole matrix has been wrapped in the extra layer.

In [58]:
res = none_example_tensor[None]
print(res)
res.shape

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])


torch.Size([1, 4, 3])

By placing `None` on the second axis, we'll create a new axis at the second position - each row of the matrix will be wrapped as a separate one-row matrix.

In [56]:
res = none_example_tensor[:, None]
print(res)
print(res.shape)

tensor([[[ 0,  1,  2]],

        [[ 3,  4,  5]],

        [[ 6,  7,  8]],

        [[ 9, 10, 11]]])
torch.Size([4, 1, 3])


By placing `None` on the last axis, we create a new axis as the most nested axis - each number of the input tensor is now a small one-element vector.

In [59]:
res = none_example_tensor[:, :, None]
print(res)
print(res.shape)

tensor([[[ 0],
         [ 1],
         [ 2]],

        [[ 3],
         [ 4],
         [ 5]],

        [[ 6],
         [ 7],
         [ 8]],

        [[ 9],
         [10],
         [11]]])
torch.Size([4, 3, 1])
