## Transformations

There are many reasons why tensors might need their dimensionality changed, such as how elements are organized within the tensor. This page focuses on the tools provided by PyTorch for altering tensor dimensionality.

In [1]:
import torch

## Reshape


The easiest way to change the dimensionality of a tensor is to use the `torch.reshape` function or `torch.torch.reshape` method of the tensor you're reshaping. All you have to do is specify a new dimensionality, quite obviously the number of elements in the new dimensionality must be equal to the number of elements in the tensor to be reshaped.

---

Consider an example with 12 arange elements.

In [3]:
original_tensor = torch.arange(12)
print("original", original_tensor)

original tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


The following cell reshapes it to the `(6, 2)` dimensionality.

In [ ]:
original_tensor.reshape(6,2)

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])

The elements are sequentially obtained in their order, and first fill the innermost dimension, then the next one, and so on.

Same result with more complex result dimentionality.

In [ ]:
original_tensor.reshape(3,2,2)

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

Similarly, when reshaping complex dimensions, it will extract elements from the most nested dimensions. The following example breaks the original sequence of elements with transposition, and then reshapes the resulting array to the 1D dimensionality.

In [ ]:
transposed_tensor = original_tensor.reshape(2, 6).T
print("Transposed \n", transposed_tensor)

transposed_tensor.reshape(12)

Transposed 
 tensor([[ 0,  6],
        [ 1,  7],
        [ 2,  8],
        [ 3,  9],
        [ 4, 10],
        [ 5, 11]])


tensor([ 0,  6,  1,  7,  2,  8,  3,  9,  4, 10,  5, 11])

It takes elements from inndermost dimentionalty gradually moving to more and more external dimensions. 

### Complete dimentionality

When using `-1` as an argument in the `reshape` function, you instruct PyTorch to automatically determine the appropriate dimension size that will match the total number of elements in the tensor.

---

Applying the `reshape(-1, 6)` instruction to the `original_tensor` from the previous examples, which contains 12 elements, tells PyTorch to automatically determine the appropriate size for the first dimension. In this case, it calculates that the size of the first dimension should be `2`.

In [ ]:
original_tensor.reshape(-1, 6)

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

For a more complex scenario, suppose we want to create 2 matrices with 3 columns each. To accommodate the 12 elements, each matrix must have 2 rows. The following example demonstrates how to achieve this using the `reshape` function:

In [ ]:
original_tensor.reshape(2, -1, 3)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])

If it’s not possible to match the dimensions, PyTorch will display an error message indicating the issue. It is not possible to arrange 12 elements into 3 matrices with 3 rows each, so this will result in an error.

In [ ]:
original_tensor.reshape(3,3,-1)

RuntimeError: shape '[3, 3, -1]' is invalid for input of size 12

## Transpose

This is tranformation that switches order of the dimentions in the elements. If we had element with diemitonality $(d_1, d_2, ..., d_i, ..., d_j, ..., d_n)$ in tensor where dimentions $i$ and $j$ it'll have dimentionality $(d_1, d_2, ..., d_j, ..., d_i, ..., d_n)$.

---

We'll try to switch the dimensions for the tensor defined in the following elements.

In [2]:
original_tensor = torch.arange(24).reshape(2, 3, 4)
original_tensor

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

This tensor can be written as $X = \left[x_{ijk}\right]_{2,3,4}$. So it's idmentionality is $(d_1, d_2, d_3)$.

Consider tensor $X'=\left[x'_{jik}\right]_{3,2,4}$ - switch of the $d_1$ and $d_2$.

In [15]:
original_tensor.transpose(0,1)

tensor([[[ 0,  1,  2,  3],
         [12, 13, 14, 15]],

        [[ 4,  5,  6,  7],
         [16, 17, 18, 19]],

        [[ 8,  9, 10, 11],
         [20, 21, 22, 23]]])

In particular: $x_{2,3,1}=x'_{3,2,1}=20$

Consider tensor $X''=\left[x''_{kji}\right]_{4,3,2}$ - switch of the $d_1$ and $d_3$.

In [12]:
original_tensor.transpose(0,2)

tensor([[[ 0,  8],
         [ 4, 12]],

        [[ 1,  9],
         [ 5, 13]],

        [[ 2, 10],
         [ 6, 14]],

        [[ 3, 11],
         [ 7, 15]]])

In particular: $x_{1,2,3}=x''_{3,2,1}=6$

Consider tensor $X'''=\left[x'''_{2,4,3}\right]$ - switch of the $d_2$ and $d_3$.

In [16]:
original_tensor.transpose(1,2)

tensor([[[ 0,  4,  8],
         [ 1,  5,  9],
         [ 2,  6, 10],
         [ 3,  7, 11]],

        [[12, 16, 20],
         [13, 17, 21],
         [14, 18, 22],
         [15, 19, 23]]])

In particular: $x_{2,2,3}=x'''_{2,3,2}=18$.

### `T` attribute

For two-dimensional tensors, you can use the `T` attribute to obtain the transposed tensor. This method works in older versions of PyTorch, but it is recommended to use the `T` attribute only for two-dimensional tensors.

---

The following example shows the use of the `T` attribute for the first matrix of the tensor `original_tensor`.

In [6]:
original_tensor[0].T

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])