# nn.Module class

Is a class that allows you to define complex neural networks in Torch. Simply use this class as a descendant.

In [2]:
import torch
from torch import nn

## `parameters()`

<a href="https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.parameters">Official documentation</a>.

To optimise the network, you need access to the parameters that will change as the model is optimised. The `Parameters` method fulfils this role. It looks like it somehow understands that the fields it contains are descendants of the class `nn.Module` and extracts their `parameters`.

Two following cells allow you to compare what `parameters` return if we use just empty ancestor of `nn.Module` and ancestor that have some fields that actually implementations of `nn.Module`.

In the following cell we have an empty `nn.Module` - so when we try to unpack it generator to list we have just an empty list:

In [45]:
class EmptyNetwork(nn.Module):
    pass
empty_network = EmptyNetwork()
[i for i in empty_network.parameters()]

[]

This cell implements such a descendant of the `nn.Module`, taking some parameters from its files. To be more specific, there are two fully connected layers defined here. So we end up with four tensors, two matrices for fully connected layers and their biases:

In [68]:
class ParametersNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.foo = nn.Linear(3, 3)
        self.bar = nn.Linear(5, 5)

network = ParametersNetwork()
for i in network.parameters():
    print(i.data)

tensor([[ 0.0302, -0.4218,  0.3589],
        [ 0.0500, -0.0864,  0.2156],
        [-0.5365,  0.4816,  0.2940]])
tensor([-0.0345, -0.4456, -0.4284])
tensor([[ 0.1643,  0.3919,  0.4324, -0.2549,  0.0276],
        [-0.0170,  0.2218, -0.3960,  0.1335,  0.3155],
        [ 0.0246, -0.0172,  0.3138,  0.4222,  0.0569],
        [ 0.2502,  0.3730, -0.1723,  0.1000,  0.1558],
        [ 0.2668, -0.3949,  0.1780,  0.2885,  0.2406]])
tensor([-0.0279, -0.2638,  0.1210, -0.1394, -0.0539])
