**В numpy, как оказалось можно настроить вывод инофрмации на в консоль, делается это с помощью функции `set_printoptions`, которой и посвящена эта книжка**, далее я постепенно разбираю аргументы функции, распространенные и интерестные случаи из моей практики связанные с этой функцией.

In [1]:
import numpy as np

np.random.seed(1)
# эксперементальный набор данных, который будет исопльзоваться для описания большинства примеров
arr = np.random.uniform(-10, 10, 20)

# Источники информации

- https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html.

# `precision`

Позволяет настроить сколько знаков после запятой `numpy` будет отображать. По умолчанию 8.

In [2]:
print("precision = 3")
np.set_printoptions(
    precision = 3
)
print(arr)
print("precision = 5")
np.set_printoptions(
    precision = 5
)
print(arr)

precision = 3
[-1.66   4.406 -9.998 -3.953 -7.065 -8.153 -6.275 -3.089 -2.065  0.776
 -1.616  3.704 -5.911  7.562 -9.452  3.409 -1.654  1.174 -7.192 -6.038]
precision = 5
[-1.65956  4.40649 -9.99771 -3.95335 -7.06488 -8.15323 -6.2748  -3.08879
 -2.06465  0.77633 -1.61611  3.70439 -5.91096  7.56235 -9.45225  3.40935
 -1.6539   1.1738  -7.19226 -6.03797]


# `threshold`

Позволяет настроить насколько большие массивы будут выводиться без "сокращения". (По умолчанию 1000)

In [3]:
print("threshold = 20; приведёт к полному отображению массива")
np.set_printoptions(threshold = 20)
print(arr)
print("threshold = 19; приведёт к сокращенному отображению массива")
np.set_printoptions(threshold = 19)
print(arr)

threshold = 20; приведёт к полному отображению массива
[-1.65956  4.40649 -9.99771 -3.95335 -7.06488 -8.15323 -6.2748  -3.08879
 -2.06465  0.77633 -1.61611  3.70439 -5.91096  7.56235 -9.45225  3.40935
 -1.6539   1.1738  -7.19226 -6.03797]
threshold = 19; приведёт к сокращенному отображению массива
[-1.65956  4.40649 -9.99771 ...  1.1738  -7.19226 -6.03797]


# `edgeitems`

Укажет сколько в сокращенном отображении массива должно элементов отображаться с каждой стороны. По умолчанию 3.

In [4]:
np.set_printoptions(
    edgeitems=3,
    threshold=0 #для того, 
    # чтобы заставить любой массив
    # отображаться в сокращенной форме
)
print("edgeitems=3")
print(arr)
np.set_printoptions(
    edgeitems=5
)
print("edgeitems=5")
print(arr)

edgeitems=3
[-1.65956  4.40649 -9.99771 ...  1.1738  -7.19226 -6.03797]
edgeitems=5
[-1.65956  4.40649 -9.99771 -3.95335 -7.06488 ...  3.40935 -1.6539
  1.1738  -7.19226 -6.03797]


# `linewidth`

Сколько символов будет отображено в каждой строке, по умолчанию используется 75. `[` и `\n` тоже учитываются. Потому всегда получается на 3 символа из массива меньше. Похоже результат приблизительный, потому как указанное `linewidth` может быть не кратно числу символов матрицы. Более того, строки бывают разные - минусы, и значение аргумента `precision` будут влиять на длинну строк.<br>


Вот пару примеров

`linewidth = 40`

In [5]:
np.set_printoptions(
    linewidth = 40,
    threshold=1000 # для того, чтобы вне зависимости
    # от предыдущих дейсвий отображался полный массив
)
print(arr)

print("Число символов по строкам (\\n был удален)")
matr_strs = str(arr).split("\n")
[len(s) for s in matr_strs]

[-1.65956  4.40649 -9.99771 -3.95335
 -7.06488 -8.15323 -6.2748  -3.08879
 -2.06465  0.77633 -1.61611  3.70439
 -5.91096  7.56235 -9.45225  3.40935
 -1.6539   1.1738  -7.19226 -6.03797]
Число символов по строкам (\n был удален)


[36, 36, 36, 36, 37]

`linewidth = 20`

In [6]:
np.set_printoptions(
    linewidth = 20,
    threshold=1000 # для того, чтобы вне зависимости
    # от предыдущих дейсвий отображался полный массив
)
print(arr)

print("Число символов по строкам (\\n был удален)")
matr_strs = str(arr).split("\n")
[len(s) for s in matr_strs]

[-1.65956  4.40649
 -9.99771 -3.95335
 -7.06488 -8.15323
 -6.2748  -3.08879
 -2.06465  0.77633
 -1.61611  3.70439
 -5.91096  7.56235
 -9.45225  3.40935
 -1.6539   1.1738
 -7.19226 -6.03797]
Число символов по строкам (\n был удален)


[18, 18, 18, 18, 18, 18, 18, 18, 17, 19]

# `suppress`

Определяет, будет ли использована экспоненциальная форма записи числа. В случае `True` числа всегда будут печататьсяв привычном формате, будучи сокращенными в соответствии со значением аргумента `precision`. В случае `False`, если в массиве находится число менее 0.0001 или отношение максимального и модуля минимального элемента массива составляет более 1000, весь массив будет напечатан в экспоненциальной форме. По умолчанию всегда `False`.

### Одно маленькое число (<0.0001)

In [7]:
unavailible_number = np.array([0.000099])
availible_number = np.array([0.0001])

np.set_printoptions(
    suppress = True,
    linewidth = 20, # это для того, чтобы числа
    # помещались в вывод
    precision = 8 # это чтобы числа, которые я указал
    # не округлились автоматически
)

print("=================suppress = True================")
print("availible number", availible_number)
print("unavailible number", unavailible_number, end = "\n\n\n")

np.set_printoptions(suppress = False)

print("=================suppress = False================")
print("availible number", availible_number)
print("unavailible number", unavailible_number)

=================suppress = True================
availible number [0.0001]
unavailible number [0.000099]


=================suppress = False================
availible number [0.0001]
unavailible number [9.9e-05]


### Отношение максимального числа к минимальному составляет более 1000

In [19]:
availible_arr = np.array([1.0, 1000])
unavailible_arr = np.array([1.0, 1001])

np.set_printoptions(
    suppress = True,
    linewidth = 20, # это для того, чтобы числа
    # помещались в вывод
    precision = 8 # это чтобы числа, которые я указал
    # не округлились автоматически
)

print("=================suppress = True==================")
print("unavailible arr", unavailible_arr)
print("availible arr", availible_arr, end="\n\n\n")

np.set_printoptions(suppress = False)
print("=================suppress = False==================")
print("unavailible arr", unavailible_arr)
print("availible arr", availible_arr, end="\n\n\n")

=================suppress = True==================
unavailible arr [   1. 1001.]
availible arr [   1. 1000.]


=================suppress = False==================
unavailible arr [1.000e+00
 1.001e+03]
availible arr [   1. 1000.]




### Заметим, что это работет только для массивов типа `float`

In [26]:
np.set_printoptions(suppress = False)

print("int не меняются")
ints_arr = np.array([1, 1001])
print(ints_arr, end = "\n\n\n")

floats_arr = np.array([1.0, 1001])
print("float меняется")
print(floats_arr)

int не меняются
[   1 1001]


float меняется
[1.000e+00
 1.001e+03]


# `nanstr` 

Позволяет настроить как будет отображен `np.NaN` в коммандном окне. По умолчанию `'nan'`.

In [11]:
np.set_printoptions(nanstr = "Нет данных")

nan_arr = np.fromfunction(
    lambda i, j: np.where(
        (i+j)%2, 0, np.NaN
    ),
    (4,4)
)

nan_arr

array([[Нет данных,         0., Нет данных,         0.],
       [        0., Нет данных,         0., Нет данных],
       [Нет данных,         0., Нет данных,         0.],
       [        0., Нет данных,         0., Нет данных]])

# `infstr`

Позволяет настроить как будет отображент np.inf в коммандном окне. По умолчанию `'inf'`

In [17]:
np.set_printoptions(infstr = "Бесконечность")

nan_arr = np.fromfunction(
    lambda i, j: np.where(
        (i+j)%2, -np.inf, np.inf
    ),
    (4,4)
)

nan_arr

array([[ Бесконечность, -Бесконечность,  Бесконечность, -Бесконечность],
       [-Бесконечность,  Бесконечность, -Бесконечность,  Бесконечность],
       [ Бесконечность, -Бесконечность,  Бесконечность, -Бесконечность],
       [-Бесконечность,  Бесконечность, -Бесконечность,  Бесконечность]])

# `sign`

Позволяет определить как будет при выводе записан символ `+` для положительных дробных чисел, может принимать значения:

- `'-'` будет обозначать, что знак `+` следует просто опускать;
- `'+'` будет обозначать, что знак `+` будет явно записан;
- `' '` будет обозначать, что знак на месте каждого знака `+` будет помещен `' '` (пробел).

По умолчанию используется значение `'-'`.

In [42]:
np.set_printoptions(
    sign = '-',
    linewidth = 10
)
print(np.array([1.0]))

np.set_printoptions(sign = '+')
print(np.array([1.0]))

np.set_printoptions(sign = ' ')
print(np.array([1.0]))

[1.]
[+1.]
[ 1.]


### Замети, что это работает только для типа данных `float`

In [43]:
np.set_printoptions(sign = ' ')
np.array([1])

array([1])

### Это не работает когда `numpy` подгоняет под отображение матрицей

В следующем примере, по идее, не отрицательные числа должны не иметь пробелов вместо минуса, но для того, чтобы матрица была "ровная", подставляется побел.

In [48]:
np.set_printoptions(
    sign = '-',
    linewidth = 40
)
arr

array([-1.65955991,  4.40648987,
       -9.9977125 , -3.95334855,
       -7.06488218, -8.1532281 ,
       -6.27479577, -3.08878546,
       -2.06465052,  0.77633468,
       -1.61610971,  3.70439001,
       -5.91095501,  7.56234873,
       -9.45224814,  3.4093502 ,
       -1.65390395,  1.17379657,
       -7.19226123, -6.03797022])